[project]
name = "best-practice-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aider-chat[playwright]>=0.83.1",
]
